# Pipeline CI/CD para Aplicación de Contabilidad Mundial
# Se ejecuta automáticamente en cada push a main y pull requests

name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente

env:
  AZURE_WEBAPP_NAME: svyd-contabilidad-app
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Setup .NET Core SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore dependencies'
      run: dotnet restore SvydProyectoMundial.sln

    - name: 'Build application'
      run: dotnet build SvydProyectoMundial.sln --configuration Release --no-restore

    - name: 'Publish application'
      run: dotnet publish SvydProyectoMundial.sln -c Release -o ./publish

    - name: 'Upload artifact for deployment job'
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Azure
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: 'Download artifact from build job'
      uses: actions/download-artifact@v4
      with:
        name: .net-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}